language: c
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      osx_image: xcode7.3

script:
  - chmod +x tools/linux/* && chmod +x tools/osx/* && cd src 
  - make full
  - ls -al haribote.img
